### PR TITLE
Add DNF command for Linux updates

### PR DESCRIPTION
**Pull request by x1101**
# Pull Request

## Issue

N/A

## Description

Adding "dnf" update command for other versions of Linux

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the projects associated license.

### CODE REVIEW

**Comment by x1101** [comment]
@SamErde I'm unsure what these failures mean. Any thoughts on how to clean them up (or, if they need cleaned up) before this minor change is good for merge?

**Comment by SamErde** [comment]
I'll have to review those, but in the meantime, can you actually commit these changes to the module's source file at https://github.com/SamErde/PSPreworkout/blob/main/src/PSPreworkout/Public/Update-AllTheThings.ps1?

The version in the scripts folder is built separately from the source and adds additional metadata so it can be published as a standalone script to the PowerShell Gallery.

Thanks!

**Comment by x1101** [comment]
Does the change need to be in both files, or will the one I modified pick it up from the one you noted?

**Comment by SamErde** [comment]
Just the one under /src is fine. 

If you look in the /Scripts folder, you'll see that I have a specific build script for that copy. 🤓

**Review by SamErde — APPROVED** [review]

**Pull request merged**
